### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by mbugert** [ties/compal_CH7465LG_py#12]
Hi @ties,
thanks for your work on this library. Would you mind releasing it on pypi so that downstream libraries can make use of it easily? That would be great.

**Comment by ties** [comment]
Hi,

I guess that would be a good idea! Better than other projects vendoring it.

Do you have an example setup.py I should follow? My last ones are not up to
date.

-Ties

**Comment by mbugert** [comment]
That's great to hear. Here's a recent one of mine, maybe you can use it as a template: https://github.com/mbugert/connectbox-prometheus/blob/master/setup.py

**Comment by ties** [comment]
That was a while since I had that setup :).

Anyway: https://pypi.org/project/compal/0.1.1/ . Please let me know if this release works for you!

**Comment by mbugert** [comment]
Yes, it works. Thank you! :+1: 
I will be integrating it into my prometheus exporter.

**Comment by ties** [comment]
That is a nice project! I never got around to making that (back then I would have pushed it directly into influxdb) but I really like that idea.

If you have changes that use aiohttp or have additional parsing logic (like in https://github.com/mbugert/python-connect-box/commit/252cfb7484592563ba510e50fa16f640ab06b4db) I would welcome them, I think it would improve this library.
