### ISSUE TITLE
wlBandMode2g and wlBandMode

### ISSUE THREAD

**Issue by chefsichter** [ties/compal_CH7465LG_py#17]
https://github.com/ties/compal_CH7465LG_py/blob/ef3b1644c71d390fa8f5e81cc5fc9b688ed1dd0e/compal/__init__.py#L616

Hello Ties

I'm Felix from Switzerland. Thanks a lot for your code. Nearly everything worked.

My modem type is ...

  - Hardware Version: 5.01
  - Software Version: CH7465LG-NCIP-6.12.18.26-3p4-GA-NOSH

...from UPC Switzerland

I've tried to write a **python program that shuts off WIFI over night**, because my provider hasn't done that in his javascript solution.

I see the following in the javascript code of my provider:
```
    if(wlBandMode2g==1){      
        if(wlBandMode5g==1){
            wlBandMode=3;  //concurrent
        }else if(wlBandMode5g==2){
            wlBandMode=1;  //2g
        }
    }else if(wlBandMode2g==2){     
        if(wlBandMode5g==1){
            wlBandMode=2;  //5g
        }else if(wlBandMode5g==2){
            wlBandMode=4;  //off
        }       
    }
```
For me that means:
-  (wlBandMode=1) means 2g is on an 5g is off
-  (wlBandMode=2) means 2g is off an 5g is on
-  (wlBandMode=3) means 2g is on an 5g is on
-  (wlBandMode=4) means 2g is off an 5g is off

I've also seen, that my provider uses fun:319 to set the WIFI settings  (also on/off states of radio):

Following **strange behavior** of the router i asserted:
When i for example set wlBandMode:4 over 319, the 2g turns off and also the 5g turns off, like it should be. For all the other (1-4) it also works. What is special is that when i get wifi-settings (from fun:315 and fun:300) Bandmode always stay the same, namely Bandmode:3. It never changes from 3 to 4, or from 3 to 2 or 1. It always stays Bandmode:3. (See xml in router below, after setting wlBandMode:4 via fun:319)

FROM GETTING (fun:315) IN ROUTER AFTER SETTING 'wlBandMode:4' (via fun:319):
`<Bandmode>3</Bandmode><BssEnable2g>2</BssEnable2g><BssEnable5g>2</BssEnable5g>`

FROM GETTING (fun:326) IN ROUTER AFTER SETTING 'wlBandMode:4' (via fun:319):
`<primary24g>0</primary24g><primary5g>0</primary5g>`
_(I only see here, that both 2g and 5g are really off)_

FROM GETTING (fun:300) IN ROUTER AFTER SETTING 'wlBandMode:4' (via fun:319):
`<Bandmode>3</Bandmode><BssEnable2g>2</BssEnable2g><BssEnable5g>2</BssEnable5g>`

Because Bandmode never changes, the following code doesn't work for me:
`mode=bool(xml_value("Bandmode") & band_number)`

by setting via fun:301,  like you do it in your code, i could only turn off both (2g and 5g) if, i use
```
wlBandMode2g:2
wlBandMode5g:2
```
as setting parameters.

Your code reads from fun:300 and gives always the following values back (because for me Bandmode is always 3)
```
wlBandMode2g: True [bool(3 & 2)]
wlBandMode5g: True [bool(3 & 5)]
```
When i try to change the following values and to set via fun:301 like this...
```
wifi = WifiSettings(modem)
settings = wifi.wifi_settings
settings.radio_2g.mode = True [Annotation: or False]
settings.radio_5g.mode = True [Annotation: or False]
settings.radio_2g.bss_enable = True [Annotation: or False]
settings.radio_5g.bss_enable = True [Annotation: or False]
wifi.update_wifi_settings(settings)
```
... i doesn't work because my router accepts only integers. Like above written settings.radio_2g.mode = 1 [Annotation: or 2] works to change the on/off state. For bss_enable = ? i didn't found an integer to set it correctly (also True/False doesn't work).

Do you experience the same behavior?
Over 319 i could set bandmode.

best regards
Felix

**Comment by ties** [comment]
Hi,

Thanks for your issue. Your analysis was detailed and I think your analysis is correct. This looks like a bug. Unfortunately I can not debug this easily since I can not change these settings on my connectbox (it is not activated).

I think that both the parsing and the setting of the `wlBandMode` is broken and would need to be changed. A direct setter for `319` would also be nice.

So there are bugs near
https://github.com/ties/compal_CH7465LG_py/blob/ef3b1644c71d390fa8f5e81cc5fc9b688ed1dd0e/compal/__init__.py#L616

I would really welcome the contribution if someone is interested in editing this (or if it is already present in a fork). I tried to change it on my modem but the WiFi settings are locked so I can not debug this.

**Comment by JJYi1** [comment]
Hi @chefsichter,
May I ask if the syntax of the request body for setter fun=319 should be like this:
token=token&fun=319&wlBandMode=3?
I tried this but got a 400 - Bad Request error. Could you please advise?

Thanks a lot!
