### ISSUE TITLE
Vodafone CH7465VF - Issue with login

### ISSUE THREAD

**Issue by fsck-block** [ties/compal_CH7465LG_py#38]
Hi,

Just for information

I got an software update for my Vodafone COMPAL CH7465VF and the posted data seems now to be a bit different.

Firmware: CH7465VF-NCIP-6.15.20.2-2-NOSH

I got the error during login and after some traffic monitoring i realized that the sessionToken is no longer part of the posted data.

So commented out lines 147,148 from compal/__init__py 
`        # if self.send_token:`
`            #     data["token"] = self.session_token `

With this fix it is possible to login and to list the functions as shown in example.

**Comment by frimtec** [comment]
Guess you can use the new constructor parameter  `send_token` and set it to `False` to do exactly that without changing the code.
Was just introduced by @7FM.

**Comment by 7FM** [comment]
> Guess you can use the new constructor parameter send_token and set it to `False` to do exactly that without changing the code.

Yes this is exactly why I introduced this flag in https://github.com/ties/compal_CH7465LG_py/commit/14d5f7427df4ca992c0e4a29f8d23016baa2c0fb :)

**Comment by fsck-block** [comment]
Opps. You are right
Sorry for that

**Comment by frimtec** [comment]
> > Guess you can use the new constructor parameter send_token and set it to `False` to do exactly that without changing the code.
> 
> Yes this is exactly why I introduced this flag in [14d5f74](https://github.com/ties/compal_CH7465LG_py/commit/14d5f7427df4ca992c0e4a29f8d23016baa2c0fb) :)

By the way, thanks a lot for your change 👍🏻
